[package]
name = "deimos"
version = "0.0.0"
edition = "2024"
default-run = "deimos"

[[bin]]
name = "deimos"
path = "src/main.rs"

[workspace]
members = [
    "crates/core",
    "crates/d3d12",
    "crates/data",
    "crates/ecs",
    "crates/egui-d3d12",
    "crates/egui-sdl3-platform",
    "crates/render",
    "crates/umbra3",
]

[workspace.dependencies]
anyhow = "1"
crossbeam = "0.8"
egui = { version = "0.33", default-features = false, features = ["bytemuck"] }
egui_dock = "0.18"
glam = { version = "0.29", features = ["bytemuck", "fast-math"] }
itertools = "0.14"
hecs = "0.10.5"
parking_lot = "0.12"
potassium = "0.4.3"
profiling = "1"
rayon = "1.11.0"
serde = "1"
sdl3 = { version = "0.16", features = [
    "raw-window-handle",
] }
tiger-parse = { version = "0.7.2", git = "https://github.com/v4nguard/tiger-parse.git", features = [
    "check_types",
    "check_types_strict",
    "tiger_pkg",
    "check_types_debug",
] }
tiger-pkg = { version = "0.20", features = ["global_manager_instance"] }
tracing = { version = "0.1" }

[workspace.dependencies.windows]
version = ">=0.59, <=0.62"
features = [
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Foundation",
    "Win32_System_Console",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Security",
    "Win32_System_Threading",
]

[dependencies]
deimos-core = { path = "./crates/core" }
deimos-data = { path = "./crates/data" }
deimos-ecs = { path = "./crates/ecs" }
deimos-render = { path = "./crates/render" }
d3d12 = { path = "./crates/d3d12" }
egui-sdl3-platform = { path = "./crates/egui-sdl3-platform" }
egui-d3d12 = { path = "./crates/egui-d3d12" }
umbra = { path = "./crates/umbra3" }

# (De)serialization
serde.workspace = true
tiger-parse.workspace = true
tiger-pkg.workspace = true
toml = "0.9.10"

# General
anyhow.workspace = true
bitflags = "2"
bytemuck = "1.22.0"
itertools.workspace = true
parking_lot.workspace = true
profiling.workspace = true
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "fmt",
    "std",
    "tracing-log",
] }
tracing.workspace = true
tracy-client = { version = "0.18.4", optional = true }

# Graphics
glam.workspace = true
sdl3.workspace = true

# UI
ahash = "0.8.12"
chroma-dbg = "0.2.1"
clap = { version = "4.5.37", features = ["derive"] }
egui.workspace = true
egui_dock.workspace = true
egui_extras = { version = "0.33", features = ["image"] }
google_material_symbols = "0.2.9"
hecs.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
native-dialog = "0.7.0"
nu-ansi-term = "0.50.1"
rayon.workspace = true

[build-dependencies]
embed-resource = "3.0.1"

[profile.dev.package.tiger-pkg]
opt-level = 3

[profile.dev.package.deimos-data]
opt-level = 3

[profile.profiling]
inherits = "release"
debug = true

[features]
tracy = ["profiling/profile-with-tracy", "dep:tracy-client"]
