[package]
name = "deimos-render"
version = "0.1.0"
edition = "2021"

[dependencies]
deimos-core = { path = "../core" }
deimos-data = { path = "../data" }
d3d12 = { path = "../d3d12" }

anyhow.workspace = true
assert-offset = "0.1"
bytemuck = { version = "1", features = ["derive"] }
chroma-dbg = "0.1.1"
crossbeam.workspace = true
ddsfile = "0.5.2"
glam.workspace = true
int-enum = "1.2.0"
itertools.workspace = true
lazy_static = "1"
parking_lot.workspace = true
profiling.workspace = true
rand = "0.9.0"
raw-window-handle = "0.6.2"
rayon.workspace = true
sdl3.workspace = true
smallvec = "1.14.0"
tiger-parse.workspace = true
tiger-pkg.workspace = true
tracing.workspace = true
windows.workspace = true
petgraph = "0.8.3"
gpu-allocator = { version = "0.28.0", default-features = false, features = ["d3d12", "std"] }
potassium.workspace = true

[features]
tracy = []
