[package]
name = "egui-d3d12"
version = "0.0.0"
edition = "2021"

[dependencies]
d3d12 = { path = "../d3d12" }
deimos-render = { path = "../render" }

bytemuck = { version = "1", features = ["derive"] }
egui.workspace = true
thiserror = "2"
gpu-allocator = { version = "0.28.0", default-features = false, features = ["d3d12", "std"] }
